# Offense count: 15
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/BooleanSymbol:
  Exclude:
    - 'lib/puppet/provider/postgresql_psql/ruby.rb'
    - 'lib/puppet/type/postgresql_psql.rb'
    - 'spec/unit/puppet/type/postgresql_psql_spec.rb'

# Offense count: 2
# Configuration parameters: AllowedMethods.
# AllowedMethods: enums
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/unit/puppet/provider/postgresql_replication_slot/ruby_spec.rb'

# Offense count: 6
# Configuration parameters: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 49

# Offense count: 8
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns, inherit_mode.
# AllowedMethods: refine
Metrics/BlockLength:
  Max: 121

# Offense count: 3
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 9

# Offense count: 6
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 31

# Offense count: 1
# Configuration parameters: CountKeywordArgs, MaxOptionalParameters.
Metrics/ParameterLists:
  Max: 6

# Offense count: 4
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 11

# Offense count: 24
# Configuration parameters: ForbiddenDelimiters.
# ForbiddenDelimiters: (?i-mx:(^|\s)(EO[A-Z]{1}|END)(\s|$))
Naming/HeredocDelimiterNaming:
  Exclude:
    - 'lib/puppet/type/postgresql_conn_validator.rb'
    - 'lib/puppet/type/postgresql_replication_slot.rb'
    - 'spec/acceptance/server/grant_spec.rb'
    - 'spec/acceptance/server/recovery_spec.rb'
    - 'spec/classes/server/config_spec.rb'
    - 'spec/classes/server/initdb_spec.rb'
    - 'spec/classes/server_spec.rb'
    - 'spec/defines/server/default_privileges_spec.rb'
    - 'spec/defines/server/grant_spec.rb'


# Offense count: 104
# Configuration parameters: Prefixes, AllowedPatterns.
# Prefixes: when, with, without
RSpec/ContextWording:
  Enabled: false

# Offense count: 73
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Enabled: false

# Offense count: 42
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 53


# Offense count: 3
RSpec/ExpectInHook:
  Exclude:
    - 'spec/unit/puppet/provider/postgresql_replication_slot/ruby_spec.rb'
    - 'spec/unit/puppet/type/postgresql_psql_spec.rb'

# Offense count: 7
# Configuration parameters: Include, CustomTransform, IgnoreMethods, SpecSuffixOnly.
# Include: **/*_spec*rb*, **/spec/**/*
RSpec/FilePath:
  Exclude:
    - 'spec/defines/server/instance/config.rb'
    - 'spec/defines/server/instance/initdb.rb'
    - 'spec/defines/server/instance/late_initdb.rb'
    - 'spec/defines/server/instance/passwd.rb'
    - 'spec/defines/server/instance/reload.rb'
    - 'spec/defines/server/instance/service.rb'
    - 'spec/unit/puppet/type/postgresql_conn_validator.rb'


RSpec/NamedSubject:
  Enabled: false

# Offense count: 2
RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/unit/puppet/provider/postgresql_replication_slot/ruby_spec.rb'

# Offense count: 63
# This cop supports safe autocorrection (--autocorrect).
RSpec/LetBeforeExamples:
  Enabled: false

# Offense count: 45
RSpec/MultipleExpectations:
  Max: 6

# Offense count: 19
# Configuration parameters: AllowSubject.
RSpec/MultipleMemoizedHelpers:
  Max: 18

# Offense count: 1
# Configuration parameters: AllowedGroups.
RSpec/NestedGroups:
  Max: 4

# Offense count: 20
# Configuration parameters: AllowedPatterns.
# AllowedPatterns: ^expect_, ^assert_
RSpec/NoExpectationExample:
  Exclude:
    - 'spec/acceptance/alternative_port_spec.rb'
    - 'spec/acceptance/default_parameters_spec.rb'
    - 'spec/acceptance/postgresql_conn_validator_spec.rb'
    - 'spec/acceptance/postgresql_psql_spec.rb'
    - 'spec/acceptance/server/grant_spec.rb'
    - 'spec/acceptance/server/recovery_spec.rb'
    - 'spec/acceptance/sql_task_spec.rb'
    - 'spec/acceptance/z_alternative_pgdata_spec.rb'
    - 'spec/unit/puppet/provider/postgresql_conn_validator/ruby_spec.rb'

# Offense count: 17
RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - 'spec/acceptance/server/grant_spec.rb'
    - 'spec/defines/server/extension_spec.rb'
    - 'spec/unit/puppet/type/postgresql_psql_spec.rb'

# Offense count: 15
RSpec/StubbedMock:
  Exclude:
    - 'spec/unit/puppet/provider/postgresql_replication_slot/ruby_spec.rb'
    - 'spec/unit/puppet/type/postgresql_psql_spec.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'lib/puppet/util/postgresql_validator.rb'

# Offense count: 2
# Configuration parameters: AllowedMethods.
# AllowedMethods: respond_to_missing?
Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/puppet/functions/postgresql/postgresql_password.rb'
    - 'lib/puppet/type/postgresql_psql.rb'
